name: Python Test Automation

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # För manuell körning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Vi installerar biblioteken direkt här istället!
        pip install pytest requests sqlalchemy pandas

    - name: Run all tests with Pytest
      run: |
        pytest